version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env_mysql
    volumes:
      - db_data:/var/lib/mysql




  jasperserver:
    #image: retriever/jasperserver:7.2.0
    image: docker-jasperserver:devel
    restart: always
    env_file:
      - .env_jasperserver
    volumes:
      # Relative path on the host/volume on container
      - jasperserver-import:/jasperserver-import
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8080:8080"

volumes:
  db_data:
  jasperserver-import:

